use_frameworks!

platform :ios, '11.0'

target '2DLiveSDK_Example' do
  pod '2DLiveSDK', :path => '../'

  target '2DLiveSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
